services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: nestdb
    command: npm run start:dev

volumes:
  pgdata:

